const  kombi =  [
    'Bloco 1: Unix, Bash e Shell Script',
    'Bloco 2: Git, GitHub e Internet',
    'Bloco 3: Introdução à HTML e CSS',
    'Bloco 4: Introdução à JavaScript e Lógica de Programação',
    'Bloco 5: JavaScript: DOM, Eventos e Web Storage',
    'Bloco 6: HTML e CSS: Forms, Flexbox e Responsivo',
    'Bloco 7: Introdução à JavaScript ES6 e Testes Unitários',
    'Bloco 8: Higher Order Functions do JavaScript ES6',
    'Bloco 9: JavaScript Assíncrono e Promises',
    'Bloco 10: Testes automatizados com Jest',
    'Bloco 11: Introdução à React',
    'Bloco 12: Componentes com Estado, Eventos e Formulários com React',
    'Bloco 13: Ciclo de Vida de Componentes e React Router',
    'Bloco 14: Metodologias Ágeis',
    'Bloco 15: Testes automatizados com React Testing Library',
    'Bloco 16: Gerenciamento de estado com Redux',
    'Bloco 17: Projeto Jogo de Trivia',
    'Bloco 18: Context API e React Hooks',
    'Bloco 19: Projeto App de Receitas',
    'Bloco 20: Introdução à SQL',
    'Bloco 21: Funções SQL, Joins e Subqueries',
    'Bloco 22: Normalização e Modelagem de Banco de Dados',
    'Bloco 23: Introdução ao MongoDB',
    'Bloco 24: MongoDB: Updates Simples e Complexos',
    'Bloco 25: MongoDB: Aggregation Framework',
    'Bloco 26: Introdução ao desenvolvimento Web com NodeJS',
    'Bloco 27: NodeJS: Camada de Serviço e Arquitetura Rest e Restful',
    'Bloco 28: Autenticação e Upload de Arquivos',
    'Bloco 29: Deployment',
    'Bloco 30: Projeto Trybeer',
    'Bloco 31: Arquitetura: SOLID e ORM',
    'Bloco 32: Sockets',
    'Bloco 33: Projeto Trybeer II',
    'Bloco 34: Arquitetura de Computadores e Redes',
    'Bloco 35: Introdução à Python e Raspagem de Dados da Web',
    'Bloco 36: Programação Orientada a Objetos e Padrões de Projeto',
    'Bloco 37: Algoritmos e Estrutura de Dados',
    'Bloco 38: Estrutura de Dados: Hash e Set',
    'Bloco 39: Estrutura de Dados: Pilhas, Filas e Listas',
    ''
  ]
